fos_rest:
    view:
        view_response_listener:  true
    format_listener:
        rules:
            - { path: ^/v2.0, prefer_extension: true, fallback_format: json, priorities: [ json ] }
